const Products = [
    {
      _id: "1",
      name: "AirPods i18 TWS",
      image: "/images/img01.jpg",
      description:
        "Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working and With Power bank",
      brand: "China",
      category: "Electronics",
      price: 14.99,
      countInStock: 10,
      rating: 3.5,
      numReviews: 12,
    },
    {
      _id: "2",
      name: "Portable SelfiSticks",
      image: "/images/img02.jpg",
      description: "I wish to Click every Moment of life in which you will happy",
      brand: "listic",
      category: "Electronics",
      price: 10.99,
      countInStock: 10,
      rating: 3.0,
      numReviews: 15,
    },
    {
      _id: "3",
      name: "Airbudss i18 TWS",
      image: "/images/img03.jpg",
      description:
        "Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working and With Power bank",
      brand: "Audionic",
      category: "Electronics",
      price: 15.99,
      countInStock: 10,
      rating: 2.5,
      numReviews: 7,
    },
    {
      _id: "4",
      name: "Safegaurd Soap",
      image: "/images/img05.jpg",
      description: "Totaly jerms Protection Safegaurd",
      brand: "Safegaurd",
      category: "Detergent",
      price: 2.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "5",
      name: "Shaving Machine",
      image: "/images/img12.jpg",
      description: "Portable and Chargeable and fully cleane your face",
      brand: "kambi",
      category: "Electronic",
      price: 10.99,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "6",
      name: "Smart Phone Samsung A10",
      image: "/images/img10.jpg",
      description: "Dual Sim 4G 10mgp camera 5mgp front Camera",
      brand: "Samsung",
      category: "Electronic",
      price: 130.99,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "7",
      name: "Winter Jogars",
      image: "/images/img15.jpg",
      description: "touch the Sky Wearing with the jogars",
      brand: "Addidas",
      category: "Leather",
      price: 30.99,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "7",
      name: "Hot Bandage",
      image: "/images/img13.jpg",
      description: "Save your Knee",
      brand: "Nylon",
      category: "Cloth",
      price: 2.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
        _id: "8",
        name: "Shan Daleem",
        image: "/images/img07.jpg",
        description: "Best Masala of Shan Recepie mix Daleem",
        brand: "Shan",
        category: "Food",
        price: 1.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: "9",
        name: "Hooks",
        image: "/images/img16.webp",
        description: "Hanged your Clothes everywhere just install your hook ",
        brand: "Nicle",
        category: "Accessories",
        price: 1.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: "10",
        name: "Frier",
        image: "/images/img11.jpg",
        description: "Make your Flavour with at home use frier and enjoy with movie",
        brand: "Panasonic",
        category: "Accessories",
        price: 105.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: "11",
        name: "Arial Blue",
        image: "/images/img06.jpg",
        description: "Totaly jerms Protection Cleane yourv Cloth without losing your cloth color",
        brand: "Arial ",
        category: "Detergent",
        price: 2.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 10,
      },
  ];
  
  export default Products;
  